language: python

matrix:
  include:
    - python: 3.7


install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - py.test -v .

notifications:
  slack: urduhack:HarNbK5WrXQbu9XuFLPsSFtM
