language: python

matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: false


install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - py.test -v .

notifications:
  slack: urduhack:HarNbK5WrXQbu9XuFLPsSFtM
